# Tentei fazer rodar o terraform aqui no workflow, 
# mas encontrei algumas dificuldades e o trabalho não me permitiu dar devida atenção à essa task, 
# mas irei verificar em como prosseguir quando tiver tempo.

name: Mensagens

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    inputs:
      message:
        description: "Mensagem para imprimir"
        required: false
        default: "Build acionado"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "${{ inputs.message }}"
          else
            echo "CI rodou no evento: ${{ github.event_name }} na ref: ${{ github.ref }}"
          fi
